vtkVmtk/DifferentialGeometry/CMakeLists.txt
vtkVmtk/Misc/CMakeLists.txt

This commit fixes the following warning happening when configuring using
CMake 3.2.1
// ----------------
CMake Warning (dev) at vtkVmtk/DifferentialGeometry/CMakeLists.txt:73 (ADD_LIBRARY):
Policy CMP0038 is not set: Targets may not link directly to themselves.
Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Target "vtkvmtkDifferentialGeometry" links to itself.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at vtkVmtk/Misc/CMakeLists.txt:50 (ADD_LIBRARY):
Policy CMP0038 is not set: Targets may not link directly to themselves.
Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Target …

Fix CMake warnings CMP0038

---

vtkVmtk/Contrib/vtkvmtkBoundaryLayerGenerator2.cxx
vtkVmtk/Contrib/vtkvmtkCellDimensionFilter.cxx
vtkVmtk/Contrib/vtkvmtkCenterlineInterpolateArray.cxx
vtkVmtk/Contrib/vtkvmtkConcaveAnnularCapPolyData.cxx
vtkVmtk/Contrib/vtkvmtkPolyBallLine2.cxx
vtkVmtk/Contrib/vtkvmtkPolyDataDijkstraDistanceToPoints.cxx
vtkVmtk/Contrib/vtkvmtkPolyDataGeodesicRBFInterpolation.cxx
vtkVmtk/Contrib/vtkvmtkSurfaceProjectCellArray.cxx

Several fixes in Contrib module have been made for support VTK6 (See #140):
- Fixed `SetInput` -> `SetInputData`
- Fixed checking availability for `vtkDijkstraGraphGeodesicPath`
- Replaced `vtkstd` -> `std`

Fixed Contrib for VTK 6

---

vmtkScripts/vmtkimagewriter.py

Now if boolean ApplyTrasform is false (default behaviour), the meta image is automatically transformed in LPI (same behaviour of other formats, default for VTK). Before this commit origin and spacing were 
lost in the output image.
If boolean ApplyTrasform is true, the RasToIjkMatrixCoefficients (default now is None) are required
and the corresponding transform is applied. Before the default value was the identity matrix, but this choice was misleading in my opinion.
Tested on images with different orientations (RAI, RAS, LPI, ASL) and different angles.

vmtkimagewriter: bug with meta image and ITKIO solved

---

distribution/homebrew/vmtk.rb

The VMTK homebrew formula only works if brew is installed in /usr/local.
This patch makes compatible with non-standard locations.

Make homebrew file work for non-/usr/local prefix

---

distribution/homebrew/vmtk.rb

In the course of getting VMTK built with homebrew, I changed a few things that you may wish to merge into master
1. VMTK doesn't require that you use the homebrew python (I have successfully built it using anaconda with the amended formula). To this end, I have set PYTHON_EXECUTABLE using `which python`.
2. Python is a run time requirement as well as build time (unless you turn off python wrapping and the Pypes stuff, I guess - but this isn't implemented in the Formula)
3. ITK is a runtime dependancy as well as build time
4. VTK automatically includes python. 
Cheers,
Rupert

Homebrew dependency tweaks

---

vmtkScripts/vmtkrenderer.py

Added functionality to change the position of a window (useful when comparing several pipelines)
Previously this worked:
`self.vmtkRenderer.WindowSize = [sizex, sizey]`
`-position sizex sizey`
Now this works as well:
`self.vmtkRenderer.WindowPosition =  [posx, posy]`
`-position posx posy`

Added functionality to change the position of a window

---

vtkVmtk/ComputationalGeometry/vtkvmtkMergeCenterlines.cxx
vtkVmtk/ComputationalGeometry/vtkvmtkPolyBall.h
vtkVmtk/Contrib/vtkvmtkPolyBallLine2.h
vtkVmtk/DifferentialGeometry/vtkvmtkFEShapeFunctions.cxx
vtkVmtk/Misc/vtkvmtkCurvedMPRImageFilter.cxx
vtkVmtk/Misc/vtkvmtkPolyDataNetworkExtraction.cxx
vtkVmtk/Misc/vtkvmtkRBFInterpolation.cxx
vtkVmtk/Misc/vtkvmtkRBFInterpolation.h
vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesScalarReader.cxx
vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKImageWriter.cxx

Slicer4 uses VTK7 and therefore VMTK had to be updated to support VTK7, too.
All the changes should be backward-compatible, so VMTK works the same way for older VTK versions.
Python scripts have not been updated for VTK7. There should have been a lot of modifications because of SetInput->SetInputData changes. It is doable, see example below, I just did not need it and if backward compatibility is not needed then the changes would be much simpler.
if vtk.VTK_MAJOR_VERSION <= 5:
somefilter.SetInput(self.brush)
else:
somefilter.SetInputData(self.brush)

Update VMTK to be compatible with VTK7

---

vtkVmtk/ComputationalGeometry/vtkvmtkMergeCenterlines.cxx
vtkVmtk/Misc/vtkvmtkPolyDataNetworkExtraction.cxx
vtkVmtk/Misc/vtkvmtkRBFInterpolation.cxx
vtkVmtk/Misc/vtkvmtkRBFInterpolation.h
vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesScalarReader.cxx
vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKImageWriter.cxx

Generic data array was only introduced in VTK7.1 and not in VTK7. Adjusted #ifdefs to build correctly with both VTK 7.1 and VTK7.1 (and later).

COMP: Made VMTK compatible with both VTK 7.0 and 7.1 (and later)

---

vmtkScripts/vmtkimagemipviewer.py

Added opacity function to `vmtkimagemipviewer.py`.
Usage: add ` -opacity 0 0.5` for a linear increasing opacity map.
add ` -opacity 0.5 0.5` for a continuous opacity of 0.5
Useful to visualize lines within the mip viewer; see attached screenshot.
The opacity is applied after the window level.
The minimum of the image also receives a opacity of 0
The maximum of the image also receives a opacity of 1
Optimizations could be added depending on the desired user input / interface.
_screenshot: decreased opacity enables visualisation of points within the MIP_

Added opacity function for vmtkimagemipviewer.py

---

vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataSurfaceRemeshing.cxx

Simple one line memory leak fix in vtkvmtkPolyDataSurfaceRemeshing.cxx
This PR is in reference to Issue #185 . 
Thank you to @normanius for identifying the problem and proposing the solution. 
@lantiga , please merge at your convenience.

fixed memory leak referenced in vmtk/vmtk issue #185

---

vmtkScripts/vmtkpathlineanimator.py
vmtkScripts/vmtksurfacesmoothing.py

Fixed improper string comparison referenced in Issue #183 
Also fixed bug in vmtkpathlineanimator.py
Thank you to @normanius for identifying the problem and proposing a solution
@lantiga please merge at your convenience.

fixed improper string comparisons referenced in vmtk/vmtk issue #183

---

vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesScalarReader.cxx
vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKImageWriter.cxx

I am trying to build vmtk with brew on MacOS X.
I have found two issues:
./distribution/homebrew/vmtk.rb :
- is not pointing to the last release
- does not recognize python 
VTK_MAJOR_VERSION : brew installs VTK 8.0.0 but the MACROS for 7 and later are set for MINOR => 1
I have fixed the second issue. For the first one I only have a hard fix on the file.

Compatibility with VTK 8.0

---

vmtkScripts/contrib/vmtkimagetonumpy.py
vmtkScripts/contrib/vmtknumpytoimage.py

fix in reference to https://github.com/vmtk/vmtk.github.com/pull/4#issuecomment-317213285 . 
by using the numpy dataset adaptor module we are getting > 2 orders of magnitude speedup on the conversion.

removed looping from numpy image conversion. significant speedups.

---

vmtkScripts/contrib/vmtkentityrenumber.py
vmtkScripts/contrib/vmtksurfaceextractannularwalls.py
vmtkScripts/contrib/vmtksurfaceextractinnercylinder.py

while fixing issues related to https://github.com/vmtk/vmtk.github.com/pull/5, the vmtkscripts2html.sh tool found that the following vmtkscripts had errors in their scriptname. this fixes those errors. 
Time to rebuild anaconda packages :)

fixed scriptname error in contrib scripts

---

vtkVmtk/vtkMacroKitPythonWrap.cmake

test for slicer extension fix.

removed problem python wrapping modules from vtk wrapping

---

vmtkScripts/vmtkimagecompare.py

Prior to VTK 6.0+, the image.SetScalarType() was used to populate
pipeline information with scalar meta-data. This function was removed in
favor of casting methods. However, As users should not be comparing
images with differing types, the code was changed to only check that
scalar types were the same between the input and reference images, and
raise an error otherwise.

Fix image compare script for newer vtk versions.

---

vmtkScripts/vmtkimageinitialization.py

quick bug fix to ensure interoperability between python 2 and 3 in
vmtkimageinitialization. This ensures that the range function recieves
an integer type, which was not guarrenteed after performing the
division.

Fix python 2-3  bug in vmtkimageinitialization.

---

vmtkScripts/contrib/vmtknumpytoimage.py

Update code to check for subclass of np.floating in order to support
future numpy warnings. Deprication warning recieved was:
```
FutureWarning: Conversion of the second argument of issubdtype from
`float` to `np.floating` is deprecated. In future, it will be treated as
`np.float64 == np.dtype(float).type`.
if np.issubdtype(self.ArrayDict['PointData'][pointKey].dtype, float)
```

update depricated numpy function.

---

vmtkScripts/contrib/vmtkdijkstradistancetopoints.py
vmtkScripts/contrib/vmtkdistancetospheres.py

removed surface.GetSource() method as this was removed from recent version of VTK
Thank you to Alain Berod for reporting at https://groups.google.com/forum/#!topic/vmtk-users/_STiPkaLWMU

Fix vmtkdistancetospheres and vmtkdistancetopoints

---

vmtkScripts/contrib/vmtkmeshaddexternallayer.py
vmtkScripts/vmtkmeshcompare.py
vmtkScripts/vmtksurfacecompare.py
vtkVmtk/ComputationalGeometry/vtkvmtkMergeCenterlines.cxx
vtkVmtk/ComputationalGeometry/vtkvmtkPolyDataCenterlines.cxx
vtkVmtk/Misc/vtkvmtkPolyDataNetworkExtraction.cxx

VTK version checks were not fully correct (did not detect VTK 8 and 9 if minor version was 0).
Fixed calculator method calls according to API change in VTK 8.1:
SetAttributeModeToUsePointData was renamed to SetAttributeTypeToPointData
SetAttributeModeToUseCellData was renamed to SetAttributeTypeToCellData
Note: I have tested C++ changes but not tested the Python file changes (I just use the C++ interface).

Fixed build errors with VTK8.1

---

vmtkScripts/vmtkbranchclipper.py

there was no method named apropriatly before.

fix branchclipper with insideout enabled. 

---

tests/test_vmtkScripts/test_vmtkimagesmoother.py
vmtkScripts/vmtkimagesmoothing.py
vtkVmtk/Segmentation/CMakeLists.txt
vtkVmtk/Segmentation/vtkvmtkAnisotropicDiffusionImageFilter.cxx
vtkVmtk/Segmentation/vtkvmtkAnisotropicDiffusionImageFilter.h

Adding additional smoothing filter to vmtkimagesmoothing using ITK an-isotropic diffusion.
The anisotropic diffusion feature includes the ability to work with 2D or 3D and on many variable types.

Feature/diffusion add an-isotropic diffusion to vmtkimagesmoothing

---

vmtkScripts/vmtkflowextensions.py

add the option to exclude boundaries from adding flow extensions on and add them everywhere else.
Use Case: many outlets and one inlet, apply the same kind of flow extension to all the outlets while exclude adding one to the inlet.
vmtk vmtkflowextensions -ifile case1_mra_vmtk_decimate_ras2_dsatrim2_ext.vtp  -centerlinesfile case1_mra_vmtk_decimate_ras2_dsatrim2_crtlines.vtp  -adaptivelength 1 -extensionratio 2.0  -transitionratio 0.75 -normalestimationratio 1 -boundarypoints 100 -interactive 1 -exclude 1 --pipe vmtksurfacewriter -ofile case1_mra_vmtk_decimate_ras2_dsatrim2_ext2.vtp

add flow extensions to all outlets except those indicated

---

vmtkScripts/vmtksurfaceconnectivity.py

Sometimes the largest region is not what you want or maybe you need multiple surfaces.
The nice thing is that this will tag each connected surface which can then be filtered in paraview.

add 'all' feature to surface connectivity with surface tags

---

tests/test_vmtkScripts/CMakeLists.txt
tests/test_vmtkScripts/test_vmtksurfacetransformtoras.py
vmtkScripts/vmtksurfacetransformtoras.py

There is a use case where Slicer registration tools are used to map different image modalities to the same image space. however if the segmentation is performed on the un-transformed image there is not an easy mapping between the different coordinate frames that such that paraview can be used.
adding invert to vmtksurfacetransformtoras.py provides the following workflow.
1. extract surface from a image volume (DSA for example) using VMTK
2. transform surface to ras (normal use case) using VMTK
3. manually/automated registration in RAS space (slicer) of DSA to MRI (SLICER)
4. transform surface in RAS space using registration transforms (SLICER)
5. apply inverse xyz2ras transform from the registered image to the registered surface to get surface that matches space of image in paraview …

add invert to transform surface from RAS back to XYZ 

---

SuperBuild.cmake

When the CMake option "USE_SUPERBUILD" is enabled, CMake treats VMTK as
an External Project which pulls its source from the local disk. By
building in this manner, the CMake configures both the compilation and
instalation step to occur at the same time with a single call to "make".
While this works when a project is built from source (the first time),
the default behavior of an external project is to not feed in the source
files as a dependency of the generated install. As a complete list of
header files is not given as input to the build step, there is nothing
to indicate that the build step should re-run. Any changes which are
made to the source directory are therefore not rebuilt in the
installation directory.
By setting the CMake External Project option BUILD_ALWAYS 1, a build …

Fixes rebuilding VMTK after change to source files.

---

CMake/vtkMacroKitPythonWrap.cmake
vtkVmtk/IO/vtkvmtkFDNEUTReader.cxx
vtkVmtk/IO/vtkvmtkTetGenReader.cxx
vtkVmtk/IO/vtkvmtkXdaReader.cxx

Fix build errors when building with recent VTK versions.
1. VTK version was reversed from 9.x to 8.2
2. FileName member variable was renamed
All changes are backward compatible.

Fix build error with new VTK 8.2

---

SuperBuild.cmake

Same major.minor version, but updated to latest patch version
fixing bugs.
For ITK, it nows compiles with gcc8.
For VTK, fix build error related to const conversion.

Update patch version of VTK and ITK

---

vmtkScripts/contrib/vmtkentityrenumber.py
vmtkScripts/vmtkcenterlinelabeler.py
vmtkScripts/vmtkimageinitialization.py
vmtkScripts/vmtkpointtransform.py
vmtkScripts/vmtksurfacecurvature.py

Division operator returns floating-point value in Python3, while an integer value in Python2.
Fixed by using integer division operator (//) when the result is used an index.
fixes #362

Fix Python3 syntax errors due to Python2-style integer division

---

CMakeLists.txt
tests/CMakeLists.txt

Make `submodule init` optional so test data can be selected or edited without overwrite during build process.

fix: make test data submodule init optional

---

tests/test_vmtkScripts/test_vmtkcenterlines.py
tests/test_vmtkScripts/test_vmtkimagefeatures.py

used script to catch fixes.
`$ for f in $(find . | ack "\.py$"); do \
echo $f; \
autopep8 --select W291,W292,W293,W391,E301,E302,E303,E304,E305,E306 --in-place $f; \
done`

STYLE: pep8 fixes

---

vmtkScripts/vmtksurfacereader.py
vmtkScripts/vmtksurfacewriter.py

Update the surface reader and writer to work with wavefront obj format.
vtk can now write ascii wavefront format "obj", https://gitlab.kitware.com/vtk/vtk/merge_requests/4045
adding obj format to writer for when vtk version gets updated, currently won't work unless vtk master is linked to vmtk. (not in latest vtk release 8.1.1) will give an error message if vtk version is less than 9 for now.
vtk could already read wavefront format so that portion already works.
also making sure the extension of the file is compared in lower case. I have seen ".PLY", ".OBJ", and "STL" in the wild.
I believe this addresses the comments in #297 although I flubbed getting git to do what I wanted.

feat: add wavefront reader/writer .obj extension

---

vmtkScripts/vmtklevelsetsegmentation.py

skip performing the cast operation in the event that the image type is of type float already.

fix: skip cast if input image is already of type float

---

vtkVmtk/Misc/vtkvmtkTopologicalSeamFilter.cxx

Set `seamArray` value for the first element of the recursive loop instead of keeping the initialization value of 0.0 in `vtkvmtkTopologicalSeamFilter.cxx`
This should solve the extra triangle remaining issue with the `vmtksurfaceendclipper` script (#169). The initialization value of 0.0 for this specific point (top of the extra triangle) makes the clipping filter believe it belongs to the clipping plane resulting in an uncut triangle
Associated post on VMTK forum: https://discourse.slicer.org/t/extra-or-missing-triangle-with-vmtksurfaceendclipper-script/20530

BUG: Fix initial seam array value never assigned

---

vmtkScripts/vmtkimagevesselenhancement.py
vtkVmtk/Segmentation/vtkvmtkVesselnessMeasureImageFilter.cxx
vtkVmtk/Segmentation/vtkvmtkVesselnessMeasureImageFilter.h

This addresses  #243 by casting the input image to float.
There is a TODO around rescaling the input image such that data is not truncated but linearly fit to the data type to reduce the data loss.
I also added the ability to run the filter on dark objects on bright background.
This does not yet include a check in the c++ for the data type and exiting nicely

feat: Add ability to filter on bright background and Cast image to float

---

vmtkScripts/contrib/CMakeLists.txt
vmtkScripts/contrib/vmtkcontribscripts.py
vmtkScripts/contrib/vmtkendpointsections.py

Adds script to extract endpoints from split and grouped centerlines.
chore: move to contrib and pep8
from: https://github.com/Clemson-MSE/vmtk/commit/1cff14b50fd75e06ef304a8d3398c93e3cb6571a
fix: license and pep8
Currenlty not tested

fix: Extract endpoint centerline sections

---

vmtkScripts/contrib/vmtknumpytoimage.py
vmtkScripts/contrib/vmtknumpytosurface.py

np.issubdtype with int or float second argument was deprecated in numpy 1.14 (https://github.com/numpy/numpy/pull/9505). This changes the argument to np.integer or np.floating which should avoid issues with recent numpy versions.

Fix deprecated numpy issubdtype calls

---

vmtkScripts/vmtkimageinitialization.py
vmtkScripts/vmtkimageseeder.py

This is in response to a [question posted on the mailing list](https://groups.google.com/forum/#!topic/vmtk-users/9YghcHqjSc8) by @kayarre and commented on by @lantiga and myself. 
This PR attempts to extend the colliding fronts method to allow for multiple seeds to be selected at the same time. The PR currently works (with a few bugs in the seed colors). 
Instead of being limited to selecting two seeds at a time, the user is allowed to input any arbitrary amount of seeds (as long as the total number is even). Every two seeds selected are assumed to belong to a single colliding front "seed pair". The colliding fronts initial level set is calculated `numSeeds / 2` times, once for each seed pair. These are then summed together to produce the "final" (combined) initial level set which is set …

Add Multiple Seed Colliding Fronts Method to vmtkImageInitialization

---

tests/test_vmtkScripts/test_vmtkcenterlinesnetwork.py
vmtkScripts/vmtkcenterlinesnetwork.py

The behavior of `vmtkcenterlinesnetwork.py` is not deterministic since this script chooses a random node through python's `random` module, which means builds can randomly fail because of this one test. I think the easiest for now would be to use the same random seed for all builds, hopefully this at least makes sure the behavior is consistent.
(Technically different python versions can affect the random generator, but as far as I can tell it has been stable since python [3.2](https://stackoverflow.com/questions/11929701/why-is-seeding-the-random-generator-not-stable-between-versions-of-python))

Set random seed for non-deterministic test

---

CMakeLists.txt
tests/CMakeLists.txt

CMake always tries to initialize the test data submodule, which can cause problems if I'm trying to build form a tarball or if git isn't available etc but still want the tests to run. 
This adds a `VMTK_TEST_SUBMODULE` option to disable this (defaults to replicating the existing behaviour)

Add CMake option to not expect test data to be a git repository

---

CMakeLists.txt

@lassoan Sorry I've accidentally added `FORCE ` to this option and it needs to be able to be modified from the command line

bugfix: VMTK_TEST_DATA_SOURCE overriding command line

---

vtkVmtk/Segmentation/itkAnisotropicDiffusionVesselEnhancementImageFilter.h

Build failed using MSVC due to inconsistent use of bool and uint_8 (see error message below). Considered using both `itk::uint8_t`, but chose to go with `uint8_t` instead as this type was already used in VMTK.
```
7>------ Build started: Project: vtkvmtkSegmentation, Configuration: Release x64 ------
7>vtkvmtkVesselEnhancingDiffusionImageFilter.cxx
7>C:\D\SlicerExtension-VMTK_R\VMTK\vtkVmtk\Segmentation\itkAnisotropicDiffusionVesselEnhancementImageFilter.txx(409,1): error C2664: 'double itk::FiniteDifferenceImageFilter<TInputImage,TOutputImage>::ResolveTimeStep(const std::vector<double,std::allocator<double>> &,const std::vector<itk::uint8_t,std::allocator<itk::uint8_t>> &) const': cannot convert argument 2 from 'std::vector<bool,std::allocator<bool>>' to 'const …
```

COMP: Fix build error on Windows

---

vtkVmtk/Misc/CMakeLists.txt
vtkVmtk/Misc/vtkvmtkStaticTemporalStreamTracer.cxx
vtkVmtk/Misc/vtkvmtkTestIntervalInformation.cxx

A backward-incompatible change was introduced in public VTK API
(IntervalInformation was renamed to vtkIntervalInformation and other related changes).
The change was not associated with a VTK version change (not even patch), therefore a compile check was added
to detect what VTK version is used and make VMTK build correctly with both the latest VTK-9.1.0 and earlier versions.

COMP: Fix build with latest VTK master

---

vtkVmtk/Segmentation/itkMedialCurveImageFilter.h

std::binary_function was deprecated in C++11 and removed in C++17.
It only added typedefs. Since they were unused, it compiles fine
without them.
See: https://github.com/InsightSoftwareConsortium/ITK/commit/7b2dfd28d415d33c0138db275974735a9015fb30
binary_function is breaking the windows build on the Slicer extension factory now that we have switched to C++ 17, see:
https://slicer.cdash.org/viewBuildError.php?buildid=2733792
When this is merged, will update Slicer extension.

COMP: Remove deprecated/removed std::binary_function
