vmtkScripts/vmtkimagefeatures.py

command:
vmtklevelsetsegmentation -ifile image.vti -ofile level_sets.vti

BUG: fixed crash when starting vmtklevelsetsegmentation

---

vmtkScripts/vmtkcenterlines.py

BUG: fixed crash when selecting the seed points

---

vtkVmtk/Misc/vtkvmtkTopologicalSeamFilter.cxx

added comment and small fix to initialization bug.

comment and small initialization bug

---

vmtkApps/CerebralAneurysms/ParentVesselReconstruction/clipvoronoidiagram.py

fixed non-exisiting attribute error. 

---

vtkVmtk/Utilities/OpenNL/nl_single_file.c

addresses https://github.com/vmtk/vmtk/issues/208

fix compiler warning

---

vmtkScripts/contrib/vmtkboundarylayer2.py
vmtkScripts/contrib/vmtkdijkstradistancetopoints.py
vmtkScripts/contrib/vmtkdistancetospheres.py
vmtkScripts/contrib/vmtkgeodesicsurfaceresolution.py
vmtkScripts/contrib/vmtkmeshaddexternallayer.py
vmtkScripts/contrib/vmtkmeshclipcenterlines.py
vmtkScripts/contrib/vmtkmeshtetrahedralize2.py
vmtkScripts/contrib/vmtksurfaceresolution.py

Thank you to Alain Berod for reporting on https://groups.google.com/forum/#!topic/vmtk-users/_STiPkaLWMU!

fixed latent vtk6 issues in contrib scripts

---

vmtkScripts/vmtkrenderer.py

Needs testing on linux/windows with standard 1080p displays. works on retina macbook.

scaling text for high dpi displays

---

vmtkScripts/vmtkrenderer.py

fix bug where text would randomly rescale when using certain gui inputs
This should set a consistent font size for all machines and workflows.

text scaling fix

---

vmtkScripts/vmtkrenderer.py

Fix in reference to https://github.com/vmtk/vmtk/issues/246
@kayarre can you please test this and let me know how it works on your display?

font size should now scale based on display size

---

vmtkScripts/vmtkimagewriter.py

This addresses a work around in my workflow that bypasses the issue of #254 .
basically the vtk .vti format doesn't support generic orientation, only providing axis aligned output, however the structured grid format does.
Here is an example of how one would use this writer:
vmtkimagereader -ifile VWI_post.nrrd --pipe vmtkimagewriter -transform 1 -matrix @vmtkimagereader.xyztorasmatrix -ofile VWI_post_test.vts
vmtkimagereader -ifile VWI_post.nrrd --pipe vmtksurfacetransformtoras -ifile segmentedsurface.vtp -matrix @vmtkimagereader.xyztorasmatrix -ofile segmentedsurface_ras.vtp
VWI_post_test.vts and segmentedsurface_ras.vtp are both mapped to the same space when viewed in paraview. This is important in that segmentedsurface_ras.vtp is later used to create an unstructured volume mesh to …

add vtkXMLStructuredGridWriter to vmtkimagewriter

---

vmtkScripts/CMakeLists.txt
vmtkScripts/vmtkscripts.py
vmtkScripts/vmtksurfaceconnectivityselector.py

This module allows a user to interactively select which non-connected components of a surface they wish to keep. 
At the current time, this actually works as intended. It just needs some refactoring and tests
Demonstration video is below:
https://www.dropbox.com/s/b37zkbwm6vgokkp/surface-selector-demo.mov?dl=0

Add Interactive Surface Selection

---

tests/test_vmtkScripts/CMakeLists.txt
tests/test_vmtkScripts/test_vmtkcenterlineimage.py
tests/test_vmtkScripts/test_vmtksurfacetobinaryimage.py
vmtkScripts/CMakeLists.txt
vmtkScripts/__init__.py
vmtkScripts/vmtkcenterlineimage.py
vmtkScripts/vmtksurfacetobinaryimage.py
vtkVmtk/Segmentation/CMakeLists.txt
vtkVmtk/Segmentation/itkAverageOutwardFluxImageFilter.h
vtkVmtk/Segmentation/itkAverageOutwardFluxImageFilter.txx
vtkVmtk/Segmentation/itkMedialCurveImageFilter.h
vtkVmtk/Segmentation/itkMedialCurveImageFilter.txx
vtkVmtk/Segmentation/vtkvmtkMedialCurveFilter.cxx
vtkVmtk/Segmentation/vtkvmtkMedialCurveFilter.h

Pulls in changes from #265 into the develop-pypes branch

Centerlineimage merge into develop pypes

---

README.md

Addresses https://github.com/vmtk/vmtk/issues/284 for https://github.com/openjournals/joss-reviews/issues/745.
Specify target audience in README file.

JOSS - specify target audience

---

LICENSE

fix for https://github.com/vmtk/vmtk/pull/290
forgot to add new copyright holders on one line of the license file

joss review - typo fix

---

vmtkScripts/vmtkactivetubes.py
vmtkScripts/vmtkbifurcationvectors.py
vmtkScripts/vmtkbranchclipper.py
vmtkScripts/vmtkbranchextractor.py
vmtkScripts/vmtkbranchmapping.py
vmtkScripts/vmtkbranchpatching.py
vmtkScripts/vmtkcenterlinelabeler.py
vmtkScripts/vmtkcenterlineviewer.py
vmtkScripts/vmtkdelaunayvoronoi.py
vmtkScripts/vmtkdistancetocenterlines.py
vmtkScripts/vmtkendpointextractor.py
vmtkScripts/vmtkflowextensions.py
vmtkScripts/vmtkimageinitialization.py
vmtkScripts/vmtklevelsetsegmentation.py
vmtkScripts/vmtklocalgeometry.py
vmtkScripts/vmtkmeshboundaryinspector.py
vmtkScripts/vmtkmeshbranchclipper.py
vmtkScripts/vmtknetworkeditor.py
vmtkScripts/vmtkpointsplitextractor.py
vmtkScripts/vmtkpotentialfit.py
vmtkScripts/vmtksurfacecenterlineprojection.py
vmtkScripts/vmtksurfaceloopextraction.py

Addresses point 1 of https://github.com/vmtk/vmtk/issues/288 for https://github.com/openjournals/joss-reviews/issues/745. 
Changes included in https://github.com/vmtk/vmtk.github.com/pull/16

joss - added missing doc strings for vmtkscripts

---

doc/joss-paper/paper.md

for https://github.com/openjournals/joss-reviews/issues/745

[ci skip] typo fix on joss paper

---

README.md

For paper accepted in review https://github.com/openjournals/joss-reviews/issues/745 and complete info at https://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb

Added JOSS Paper status badge to readme

---

tests/test_vmtkScripts/CMakeLists.txt
tests/test_vmtkScripts/test_vmtkcenterlineimage.py
tests/test_vmtkScripts/test_vmtksurfacetobinaryimage.py
vmtkScripts/CMakeLists.txt
vmtkScripts/__init__.py
vmtkScripts/vmtkcenterlineimage.py
vmtkScripts/vmtksurfacetobinaryimage.py
vtkVmtk/Segmentation/CMakeLists.txt
vtkVmtk/Segmentation/itkAverageOutwardFluxImageFilter.h
vtkVmtk/Segmentation/itkAverageOutwardFluxImageFilter.txx
vtkVmtk/Segmentation/itkMedialCurveImageFilter.h
vtkVmtk/Segmentation/itkMedialCurveImageFilter.txx
vtkVmtk/Segmentation/vtkvmtkMedialCurveFilter.cxx
vtkVmtk/Segmentation/vtkvmtkMedialCurveFilter.h

Revert "Prep develop-pypes for rebase onto master"

---

vtkVmtk/Misc/vtkvmtkMeshWallShearRate.cxx

Clean up code for wall shear rate based on strain rate tensor

---

vtkVmtk/IO/vtkvmtkFDNEUTReader.cxx
vtkVmtk/IO/vtkvmtkFDNEUTReader.h
vtkVmtk/IO/vtkvmtkTetGenReader.cxx
vtkVmtk/IO/vtkvmtkTetGenReader.h
vtkVmtk/IO/vtkvmtkXdaReader.cxx
vtkVmtk/IO/vtkvmtkXdaReader.h

This fixes the readers failing to compile due to changes in vtk 9.1

fix: vtk8 backwards compatibility for readers

---

vmtkScripts/contrib/CMakeLists.txt
vmtkScripts/contrib/vmtkcontribscripts.py
vmtkScripts/contrib/vmtkpetergeneratesurface.py
vmtkScripts/contrib/vmtkpeterresurface.py
vmtkScripts/contrib/vmtkpetersurfaceclipper.py

Functionality for doing an auto clip function to repeat clips
performed on previous mesh.
from:
https://github.com/ppatalano/vmtk-petermods
commits:
0f4e88768b6ee28264b5e260c82096a12bd85887
806dfcf96dbd153f319bbeb81625792ec98edaee
fix: move files to contrib
chore: pep8
fix: rename, license, and pep8
currently untested

WIP: Autoclip on previous mesh

---

tests/test_vmtkScripts/test_vmtksurfacebooleanoperation.py
vmtkScripts/vmtksurfacebooleanoperation.py

Add optional boolean method that provides faster, and potentially
more robust boolean operation on poyldata
includes additional test to verify functionality but currently
excludes regression comparisons

feat: Alternative surface boolean method

---

vmtkScripts/vmtksurfacereader.py
vmtkScripts/vmtksurfacewriter.py

Add multiblock reader/writer support
per: https://github.com/ppatalano/vmtk-petermods/commit/32b2bcccb4eda2f9c98cd42013382597a87073d5
Currently not tested

fix: Multiblock support to reader and writer

---

vmtkScripts/vmtkdistancetocenterlines.py

Add threshold option to centerline distance

feat: Threshold centerline distance

---

vmtkScripts/vmtkcenterlinesnetwork.py

[vmtkcenterlinesnetwork](https://github.com/vmtk/vmtk/compare/master...ramtingh:disable-joblib?expand=1#diff-687f0144e9a3d0c4c2cda087065c3db703fe15a9291a0136cac192a295e9029e) uses joblib for parallel computation, however it is somewhat clunky in that 1) there is no option to turn this off, 2) its not actually supported on windows, so for windows joblib is used for serial computation which just results in unecessary overhead compared to a for loop. 
This adds a `UseJoblib` option which defaults to true on osx/linux and false on windows. This shouldn't change current behaviour, but allows users to disable joblib if they don't want multithreading (due to weird behavior on conda-forge's build systems, I expect to have to disable joblib for testing on osx and this seemed like the cleanest way …

Add an option to disable using joblib for network extraction
